### ISSUE TITLE
<what_is> is not matching `What's`

### ISSUE THREAD

**Issue by JamesSwift** [home-assistant/intents#1343]
![Capture+_2023-05-03-23-59-17](https://user-images.githubusercontent.com/2080205/236068786-dd539323-3a51-4288-b1fc-251de56ea81e.png)

As per https://github.com/home-assistant/intents/blob/40384abc2f67cb233cb058684a159bd0d57255ea/sentences/en/_common.yaml#L292 this sentence structure should match, but it fails.

**Comment by OzGav** [comment]
I can confirm this

**Comment by dontinelli** [comment]
Is this related/the same issue as reported in #1353?

**Comment by OzGav** [comment]
No I don't think so but let's see what comes of that report...

**Comment by OzGav** [comment]
Here is mine if it helps:
![image](https://user-images.githubusercontent.com/19848947/236839865-7a154d55-c054-47f4-ba2c-b76d657b4102.png)

**Comment by tetele** [comment]
> Thanks for that but why does it work with "What is the outside temperature?"

Because [you have](https://github.com/home-assistant/intents/issues/1343#issuecomment-1538383470) an entity named `Outside temperature` and `(do you know|tell me|what is) [the state of] <name> [in <area>]` is a sentence for the `homeassistant_HassGetState` intent, which matches `what is the <entity name='Outside temperature'>?`. It matches because `<name>` is an [expansion rule](https://github.com/home-assistant/intents/blob/33f4c0c161d620ff8c51b5d2e1c9bd46b195ea3d/sentences/en/_common.yaml#L288) for `[the] {name}`.

Other sentences that would work:
- do you know the state of the outside temperature?
- tell me the outside temperature
- etc

**Comment by OzGav** [comment]
Ok that's what I thought. I was just confused when you said the intents only works on areas. That PR looks like it should fix this one. I will go back to looking at the other report of mine. Thanks again.

**Comment by JamesSwift** [comment]
> @JamesSwift what is the friendly name, entity ID and alias list for your temperature sensor, please?

Hi. Sorry for the delay. The sensor name is `sensor.kitchen_temperature`. No friendly name or aliases have been defined.

**Comment by tetele** [comment]
Then your issue should be fixed in the next version of HA.
