### ISSUE TITLE
It's not possible to set the value of an input_select.

### ISSUE THREAD

**Issue by n3oney** [home-assistant/intents#1416]
It's not possible in any way to set the value of an input_select.
I've tried everything I could think of to set the value of an input_select, but I can't do it.
Getting a value is possible, and quite easy ("What is \<entity name\>?"), but setting it doesn't work :(

What would have to be done to support that action?

**Comment by tetele** [comment]
That's because we don't have intents for that yet, except for lights (brightness and color).

You could [create a custom intent](https://www.home-assistant.io/voice_control/custom_sentences/) for your specific use case.

**Comment by n3oney** [comment]
> That's because we don't have intents for that yet, except for lights (brightness and color).
> 
> 
> 
> You could [create a custom intent](https://www.home-assistant.io/voice_control/custom_sentences/) for your specific use case.

Thank you very much, I couldn’t find the page that explained this.

**Comment by n3oney** [comment]
> You could [create a custom intent](https://www.home-assistant.io/voice_control/custom_sentences/) for your specific use case.

Is there maybe a way to set the priority of intents? I’ve made two intents for my input_select that I use to turn my PC on to a given OS, or shut it down.

But, when I say „turn the PC off”, it tries to use the HassTurnOff intent instead of the custom one I created which should listen to that same phrase. Can I do anything about this?

Thanks

**Comment by tetele** [comment]
There are 2 issues here which prevent you from doing as you wish:

1. For some reason, the service `homeassistant.turn_off` works on any entity, including `input_select`. My opinion is that it shouldn't, I've raised the question and we will see what happens
2. You can't use `requires_context` in custom sentences. Even if you could, we must explicitly exclude some domains (like `input_select`) in the default intents, which seems wrong given point 1 above. HA simply should not try to turn off selects.

In general, no 2 intents should match the same sentence, although that's hard to achieve in a context where the user can name entities as he pleases. As a consequence, priorities are not something desirable.

So, short answer: you have to change something to turn off your PC:
- change the sentence so it doesn't match the default intent (e.g. "shut down the PC")
- add an `input_boolean` helper called "PC" with an automation that changes the input select when the input boolean is toggled and vice versa (no custom sentences required in this case)

Also, please describe your exact use case in detail in [a new bug report in the `core` repo](https://github.com/home-assistant/core/issues/new?assignees=&labels=&projects=&template=bug_report.yml), stating that you can't use a custom sentence because of the "turn off `input_select`" issue.
