### ISSUE TITLE
cover_HassGetState should also include Binary Sensors for all - but German as well

### ISSUE THREAD

**Issue by henne49** [home-assistant/intents#1843]
Hi, 

I have binary sensors for my windows and doors, they are not recognized when asking, as they are not in the domain cover. Can you expand the intent to include binary sensors with device class for windows?

https://github.com/home-assistant/intents/blob/main/sentences/de/cover_HassGetState.yaml
https://github.com/home-assistant/intents/blob/main/sentences/de/binary_sensor_HassGetState.yaml

Thank you

**Comment by v1k70rk4** [comment]
@henne49 Click on the binary sensor in the entities list and select the window in the 'Anzeigen als' menu :)

**Comment by henne49** [comment]
Not so user friendly and some work if you have a lot of windows.

**Comment by v1k70rk4** [comment]
It's advisable to determine during installation what each sensor controls. Otherwise, how would the system know whether it's a window or a door? It wouldn't be practical to treat every binary sensor as a cover, because then we'd assume every binary sensor is a cover... and that would lead to interesting responses to the question of how many windows are open.

Unfortunately, there's no alternative; it's necessary to specify to Home Assistant which sensor is for a window or a door.

**Comment by henne49** [comment]
It works, thank you
