### ISSUE TITLE
[Bug] Where is Person incorrectly lowercases last name.

### ISSUE THREAD

**Issue by OdinVex** [home-assistant/intents#2385]
Prompting "Where is Odin Vex?" for example would respond with "Odin vex is at Home." The last name is converted lowercase.

**Comment by tetele** [comment]
Why is it important to you? These responses are meant for voice interaction, where capitalization is not at all important.

**Comment by tetele** [comment]
I'd guess that the STT engine has transcribed your (rather uncommon) name without proper/expected capitalization. The intent recognition engine purposefully discards capitalization to avoid issues and simplify matching. Specifically in English, [the slot name is capitalized](https://github.com/home-assistant/intents/blob/766bb519f55642e39bb3914f3124261777744dc6/responses/en/HassGetState.yaml#L69) back, so as to make the sentence look pretty, but that only means the first letter of the slot.

If there are issues in a specific language, name it and we can look into it. For English, I don't see this as an issue.

**Comment by tetele** [comment]
Imagine you'd have "Odin" as an alias for the `person` entity. It's a much nicer experience to have the same name you uttered in the response than the original entity name: "Where is Odin?" "Odin Vex is at Home" - it sounds weird. More over, many have bi-lingual instances, where they have the entity name in English and aliases in another language or viceversa. Hence the use of slots in responses, as opposed to canonical entity names.

Now, slots are populated by either you typing or the STT transcribing. HA does not offer any proprietary STT engine. You use those trained by other people, which, apparently, are only good enough to transcribe "Odin vex" (lowercase V).

The very feature you are contesting is meant specifically for **voice** assistance. I can guarantee that "Odin Vex" and "Odin vex" read exactly the same when put through a TTS engine, at least in English. If that is not the case in another language, I will ask you again to name it and we can bring in the appropriate language leader to help.

I've explained what happens behind the scenes, but as you aptly pointed out, HA is an open source project. Anyone, offended or not, may contribute to making it less disrespectful "underneath". Simply being disappointed in people without the same cultural background as you not getting what the issue is won't help, neither you, nor others.

**Comment by tetele** [comment]
The complexities of this system and its components seem lost on you.

Having 2 entities named/aliased "Odin" would make Assist say that it can't decide which Odin you are referring to.

"Jr" being pronounced as "Junior" or "JRRR" is the job of the TTS engine, outside the scope of this repo.

Initially transcribing "Junior" to "Jr" falls on the STT engine, again outside the scope of this repo.

Naming an entity "Jr" or "Junior" is up to you, the used.

More often than not, there are reasons for the choices which were made in the coding by whatever generation of programmers worked on it. Changing those choices requires some new reason.

I've heard yours. I will look if it's possible to have the proper capitalization of entity names **without an uneedes, major overhaul** and only in English. But please stop being condescending about it.
