### ISSUE TITLE
[de] Spots and Strips cannot be controlled by the voice assistant

### ISSUE THREAD

**Issue by thaigner** [home-assistant/intents#2801]
I try to switch on my lamps in the living room. I have different lamps here that I have already grouped together
Lamps (spots and strips):
`
light.wohnzimmer_couch_rgb_strips
light.wohnzimmer_couch_spots
light.wohnzimmer_couch_spots
light.wohnzimmer_tv_spots
`
Groups:
`
light.wohnzimmer_licht
light.wohnzimmer_spots
light.wohnzimmer_strips
`
Switching on all the lights in the living room works but apparently spots and strips are not recognised as lights, the domain is recognised as a scene and not as a light. So I can’t switch on any spots and strips. Can I somehow add spots and strips so that they are recognised as lights by the language engine?

![image](https://github.com/user-attachments/assets/bf29890e-1976-4aa6-b67a-49f240e820d3)

regarding mchk:
the problem is not in the device domains, but in the incorrect interpretation of the phrase

**Comment by andreasbrett** [comment]
Can you post the friendly name of the spots entitity and all aliases you have set for them? Please also provide the exact sentence.

**Comment by thaigner** [comment]
light.wohnzimmer_couch_spots
- friendly name: Wohnzimmer Couch Spots
- aliase: Couch Spots; Spots

light.wohnzimmer_tv_spots
- friendly name: Wohnzimmer TV Spots
- aliase: none

light.wohnzimmer_couch_rgb_strips
- friendly name: Wohnzimmer TV RGB Strips
- aliase: 

light.eg_wohnzimmer_tv_rgb_strips
- Wohnzimmer TV RGB Strips
- aliase: 

Group:
light.wohnzimmer_strips
- friendly name: Wohnzimmer Strips
- aliase: Wohnzimmer Strips; Wohnzimmer Strip

light.wohnzimmer_spots
- friendly name: Wohnzimmer Spots
- aliase: Wohnzimmer Spots

**Comment by thaigner** [comment]
I have tried it with: 

- "TV Spots im Wohnzimmer aus": Es tut mir leid, ich konnte keine TV-Spots im Wohnzimmer finden. Es ist möglich, dass die TV-Spots nicht mehr existieren oder an einem anderen Ort installiert wurden. Bitte überprüfen Sie den Namen der Spots und versuchen Sie es erneut.
- "Spots im Wohnzimmer aus": Entschuldigung! Es scheint, dass die Spots im Wohnzimmer nicht in der Home Assistant-Konfiguration gefunden wurden. Bitte überprüfen Sie den Namen der Spots und versuchen Sie es erneut.

Alternativ können Sie auch folgende Befehle ausführen:

* HassMediaPause Spots im Wohnzimmer
* HassTurnOn Spots im Wohnzimmer

Ich hoffe, das hilft!

With the text Assist

**Comment by andreasbrett** [comment]
`TV Spots im Wohnzimmer aus`
`Strips im Wohnzimmer aus`

Both sentences will currently NOT work in your setup because of 2 reasons:

1) There are no entities with neither a name nor alias of "TV Spots" or "Strips".
2) This particular phrase ("turn <name> off in <area>") has only [recently been added](https://github.com/home-assistant/intents/pull/2786) and is not yet available in the latest HA release. It might be available with the upcoming 2025.1.x releases but I don't know the plans to update intents upstream in HA Core.

Since you're using an AI conversation agent, problem 2 could be circumvented by the AI but it seems to not be able to circumvent problem 1.

Please try "TV RGB Strips aus" (= using exact name/alias and not mentioning the area) or "TV RGB Strips im Wohnzimmer aus" (= using exact name/alias but mentioning area which is not yet supported locally but should be through AI).

**Comment by thaigner** [comment]
Thank you, that helped a lot. Just assign the right aliases and it works!
